# Strider Runner - Unity manual activation file request
# Author: Mithin Sagar S
# GitHub: https://github.com/mithinsagar
#
# One-off, manually-triggered workflow to generate a Unity manual activation
# file (.alf). Unity CI (unity-ci.yml) needs a UNITY_LICENSE secret to run
# tests and builds, and this is how you get one for a personal license:
#
#   1. Run this workflow from the Actions tab (Run workflow button).
#   2. Download the "Activation file" artifact once it finishes.
#   3. Upload the .alf file at https://license.unity3d.com/manual, signed in
#      with your Unity ID. Unity emails/returns a .ulf license file.
#   4. Add the .ulf file's contents as the UNITY_LICENSE repo secret.
#
# This workflow and its temporary Library cache can be deleted once the
# license secret is configured; it's only needed once (or again if the
# license ever needs re-issuing).

name: Unity - Request Activation File

on:
  workflow_dispatch: {}

jobs:
  request-activation-file:
    name: Request activation file
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Request manual activation file
        id: getManualLicenseFile
        uses: game-ci/unity-request-activation-file@v2
        with:
          unityVersion: 6000.4.0f1

      - name: Upload activation file
        uses: actions/upload-artifact@v4
        with:
          name: Activation file
          path: ${{ steps.getManualLicenseFile.outputs.filePath }}
          retention-days: 7
